// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiShared.Sample.DbData
{
    public partial class CHARACTERISTIC
    {
        public CHARACTERISTIC()
        {
            CHARACTERISTIC_DETAIL = new HashSet<CHARACTERISTIC_DETAIL>();
        }

        public int CHARACTERISTIC_CODE { get; set; }
        public string CHARACTERISTIC_TITLE { get; set; }

        public virtual ICollection<CHARACTERISTIC_DETAIL> CHARACTERISTIC_DETAIL { get; set; }
    }
}