// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiShared.Sample.DbData
{
    public partial class CHARACTERISTIC_DETAIL
    {
        public int CHARACTERISTIC_DETAIL_CODE { get; set; }
        public int CHARACTERISTIC_CODE { get; set; }
        public string CHARACTERISTIC_TITLE { get; set; }

        public virtual CHARACTERISTIC CHARACTERISTIC_CODENavigation { get; set; }
    }
}